In [1]:
import numpy as np

## Задание 1

Зададим коэффициенты для полинома
$$
{(x-1)(x-2)....(x-20)} = {0}
$$

In [2]:
coefs = np.array(range(1, 21))
print(coefs)
p = np.poly(coefs)
print(p)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1.00000000e+00 -2.10000000e+02  2.06150000e+04 -1.25685000e+06
  5.33279460e+07 -1.67228082e+09  4.01717716e+10 -7.56111184e+11
  1.13102770e+13 -1.35585183e+14  1.30753501e+15 -1.01422999e+16
  6.30308121e+16 -3.11333643e+17  1.20664780e+18 -3.59997952e+18
  8.03781182e+18 -1.28709312e+19  1.38037598e+19 -8.75294804e+18
  2.43290201e+18]


Найдём корни (корни действительные)

In [3]:
np.roots(p)

array([20.00003842, 18.99944526, 18.00332672, 16.98821521, 16.02622951,
       14.95636365, 14.05068644, 12.9559752 , 12.0299548 , 10.98552896,
       10.00542601,  8.9985865 ,  8.0002459 ,  6.9999773 ,  5.99999991,
        5.00000023,  3.99999998,  3.        ,  2.        ,  1.        ])

Изменим один из коэффициентов на $10^{-7}$ и заново найдём корни (стали комплексными).

In [4]:
p[1] += 1e-7
np.roots(p)

array([20.42191428+0.99919021j, 20.42191428-0.99919021j,
       18.15709998+2.47016309j, 18.15709998-2.47016309j,
       15.31451742+2.69846576j, 15.31451742-2.69846576j,
       12.84588825+2.06157319j, 12.84588825-2.06157319j,
       10.92152839+1.10102893j, 10.92152839-1.10102893j,
        9.57172741+0.j        ,  9.11219077+0.j        ,
        7.99387715+0.j        ,  7.00032223+0.j        ,
        5.99998503+0.j        ,  5.00000068+0.j        ,
        3.99999999+0.j        ,  3.        +0.j        ,
        2.        +0.j        ,  1.        +0.j        ])

Попробуем закастовать $2^{1023}$ в `float` и потом вывести его в научном формате (получилось).

In [5]:
print('{:e}'.format(2**1023))

8.988466e+307


Теперь попробуем закастовать $2^{1024}$ (не получилось, т.к. размер порядка ограничен 1024)

In [6]:
print('{:e}'.format(2**1024)) 

OverflowError: int too large to convert to float

Максимальное целое число

In [7]:
np.finfo('d').max

1.7976931348623157e+308

Минимальное целое число

In [8]:
np.finfo('d').min

-1.7976931348623157e+308

16 cимволов после запятой

In [9]:
np.sqrt(2)

1.4142135623730951

Ошибки не происходит, скорее всего, из-за того, что Python поддерживает длинную арифметику или из-за реализации функций в numpy

In [10]:
np.float_power(10, 8) + np.float_power(10,-7)

100000000.0000001

In [11]:
np.float_power(10, 8) + np.float_power(10,-8)

100000000.00000001

Считал для $10^{11}$ и $10^{10}$ и ошибки не происходило (скорее всего из-за длинной арифметики или внутреннего представления `float` в Python)
[ Хотя CPython явно представляет float как 64 битное число.]

In [12]:
summ = 1
for i in range(int(1e11)):
    summ += 1e-10
print(summ)

KeyboardInterrupt: 

При $n = 53$ происходит ошибка

In [16]:
print('n\t\teps\t\t\t\t\t\tresult')
for i in range(0, 60):
    eps = 2 ** -i
    print(f'{i:<5}\t\t{eps:<25}\t\t\t{(1+eps-1)/eps:<25}')

n		eps						result
0    		1                        			1.0                      
1    		0.5                      			1.0                      
2    		0.25                     			1.0                      
3    		0.125                    			1.0                      
4    		0.0625                   			1.0                      
5    		0.03125                  			1.0                      
6    		0.015625                 			1.0                      
7    		0.0078125                			1.0                      
8    		0.00390625               			1.0                      
9    		0.001953125              			1.0                      
10   		0.0009765625             			1.0                      
11   		0.00048828125            			1.0                      
12   		0.000244140625           			1.0                      
13   		0.0001220703125          			1.0                      
14   		6.103515625e-05          			1.0                      
15   		3.0517578125e-05         			1.0                      
16   

Из-за переполнения ответ становится неправильным -- обычная практика в олимпиадном программировании, например.

In [15]:
I = 1 / np.exp(1)
print('n\t\tI')
print(f'{1:<5}\t\t{I:<25}')
for n in range(2, 31):
    I = 1 - n * I
    print(f'{n:<5}\t\t{I:<25}')

    

n		I
1    		0.36787944117144233      
2    		0.26424111765711533      
3    		0.207276647028654        
4    		0.17089341188538398      
5    		0.14553294057308008      
6    		0.1268023565615195       
7    		0.11238350406936348      
8    		0.10093196744509214      
9    		0.09161229299417073      
10   		0.0838770700582927       
11   		0.07735222935878028      
12   		0.07177324769463667      
13   		0.06694777996972334      
14   		0.06273108042387321      
15   		0.059033793641901866     
16   		0.05545930172957014      
17   		0.05719187059730757      
18   		-0.029453670751536265    
19   		1.559619744279189        
20   		-30.19239488558378       
21   		635.0402925972594        
22   		-13969.886437139707      
23   		321308.38805421325       
24   		-7711400.313301118       
25   		192785008.83252797       
26   		-5012410228.645727       
27   		135335076174.43463       
28   		-3789382132883.17        
29   		109892081853612.92       
30   		-3296762455608386.5      


Находит правильно, если учитывать погрешностии округлять результат (например с $\epsilon$ = $10^{-16}$)

In [14]:
def mysin(x):
    u = x
    i = 1
    flag = False
    summ = u
    while True:
        u = u * (- (x ** 2) / ((2*(i-1)+2)*(2*(i-1)+3)))
        i += 1
        summ += u
        if flag:
            break
        if np.abs(u) < 1e-17:
            flag = True
    return summ

points = [0, np.pi / 3, np.pi / 2, np.pi, np.pi*2]
sins = [mysin(x) for x in points]
print(points)
print(sins)

[0, 1.0471975511965976, 1.5707963267948966, 3.141592653589793, 6.283185307179586]
[0.0, 0.8660254037844385, 1.0000000000000002, 2.4790609271195177e-16, 4.3878932039122245e-16]


Опять происходит переполнение для больших входных $x$, поэтому в реальности все подобные алгоритмы приводят входные данные
к какому-то ограниченному диапазону (очевидно, что для тригонометрических функций достаточно отрезка
от $\frac{-\pi}{2}$ до $\frac{\pi}{2}$или от $0$ до $\pi$) 

In [13]:
def mysin_print(x):
    u = x
    print('n\t\tu')
    print(f'{0:<5}\t\t{u:<25}')
    i = 1
    flag = False
    summ = u
    while True:
        u = u * (- (x ** 2) / ((2*(i-1)+2)*(2*(i-1)+3)))
        print(f'{i:<5}\t\t{u:<25}')
        i += 1
        summ += u
        if flag:
            break
        if np.abs(u) < 1e-17:
            flag = True
    return summ

x = []
x.append(mysin_print(np.pi*12))
print()
x.append(mysin_print(np.pi*13))
print()
x.append(mysin_print(np.pi*14))
print()
print(x)

n		u
0    		37.69911184307752        
1    		-8929.807683926347       
2    		634562.4183707595        
3    		-21472731.555832986      
4    		423854731.73371917       
5    		-5476291888.243632       
6    		49891231866.331665       
7    		-337650323385.4057       
8    		1764251532907.3298       
9    		-7331564081604.561       
10   		24809018443430.754       
11   		-69682111574511.336      
12   		165056370017519.22       
13   		-334162271990305.9       
14   		584875761040825.1        
15   		-893805272556234.8       
16   		1202932425236984.8       
17   		-1436668294789759.5      
18   		1532902456774330.0       
19   		-1470037975755849.5      
20   		1273934043683861.5       
21   		-1002516282597193.5      
22   		719595571991636.6        
23   		-473036911148918.7       
24   		285837990621617.4        
25   		-159309622036949.84      
26   		82153303460817.77        
27   		-39312514201256.56       
28   		17503712624598.932       
29   		-7269631665207.737       
30   